### ISSUE TITLE
Zero123 ex: What node is missing and where to get it? 

### ISSUE THREAD

**Issue by zencyon** [comfyanonymous/ComfyUI_examples#16]
Trying to use this example:
https://github.com/comfyanonymous/ComfyUI_examples/blob/master/3d/README.md

What node is missing and where to get it? 

It's called Zero123_Conditioning 
(Manager doesn't find it)
![image](https://github.com/comfyanonymous/ComfyUI_examples/assets/43258551/bd1e7361-4489-4ebb-af69-cd9b0d10d8f5)

**Comment by comfyanonymous** [comment]
Make sure you update ComfyUI: update/update_comfyui.bat or git pull

**Comment by zencyon** [comment]
oh you are right, 
it was the first thing i tried, update all & update comfy and reload server
for some reason when i did it again a second time the node showed up :)
cheers
