### ISSUE TITLE
Audio workflow missing

### ISSUE THREAD

**Issue by delolione** [comfyanonymous/ComfyUI_examples#25]
the flac audio file provided in the example has no workflow. Can you please include a link to the workflow json?

**Comment by comfyanonymous** [comment]
Update ComfyUI to the latest and it should load.

**Comment by delolione** [comment]
Awesome. Thank you.

**Comment by MushroomFleet** [comment]
sorry to bump, but i have latest version already and .flac does not load, can we get a json version of the stable audio example please? thanks if you can
