### ISSUE TITLE
Lora examples don't mention that you have to use keyword in prompt

### ISSUE THREAD

**Issue by qustrolabe** [comfyanonymous/ComfyUI_examples#5]
I'm not familiar with a all possible kinds of loras but ones that I use didn't work until I added `<lora:suzune-nvwls-v2-final:0.9>` to prompt text, it's obvious to anyone who used a1111 before but ComfyUI example covers only adding LoraLoader and don't mention anything about prompt. I think it should be fixed.

**Comment by comfyanonymous** [comment]
You don't have to use the keywords in the prompt except the recommended "activation" ones. <lora... syntax doesn't work on comfyui. It's probably the word suzune that made it work in your case.
